version: '3'
services:
          jokes-api:
              container_name: jokes-api
              image: src/jokes-api
              restart: always
              build: .
              ports: 
                - "3000:3000"
              links:
                 - mongo
          mongo:
            container_name: mongo
            image: mongo 
            volumes:
              - ./data:/data/db
            ports:
              - "27017:27017"